{
 "title": "Axelar New Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "chain_id",
    "label": "Chain ID",
    "query": {
     "query": "label_values(cvms_block_timestamp{chain=\"axelar\"},chain_id)"
    }
   },
   {
    "name": "chain",
    "label": "Chain",
    "query": {
     "query": "label_values(cvms_block_timestamp{table_chain_id=\"$chain_id\"},chain)"
    }
   },
   {
    "name": "table_chain_id",
    "query": {
     "query": "label_values(cvms_block_height{chain_id=\"$chain_id\"},table_chain_id)"
    }
   },
   { "name": "blocks", "label": "monitor_blocks", "query": "30" },
   { "name": "interval_mins", "label": "interval minutes", "query": "5" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Main content -->\n<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <!-- H2 with a link -->\n   <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n    <h2 style=\"margin-right: 10px;\">Cosmos Validator Monitoring Service (CVMS) 🌌 🔭</h2>\n  </a> \n  <!-- \"Powered by Cosmostation\" on the right -->\n  <div style=\"display: flex; align-items: center;\">\n    <a href=\"https://cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n        <span>Powered by Cosmostation </span>\n        <img src=\"https://raw.githubusercontent.com/cosmostation/chainlist/refs/heads/main/resource/cosmostation/cosmostation_color.svg\" alt=\"Logo\" style=\"height: 30px; margin-left: 5px;\">\n    </a>\n  </div>\n</div>\n\n<!-- Paragraph below the header -->\n<p>\n  The Cosmos Validator Monitoring Service (CVMS) is an open-source, integrated monitoring system designed for validators and network in the Cosmos app chain ecosystem.<br/>\n  This public dashboard is a playground for developers and beta release testing for CVMS.\n</p>\n<p>\n  <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Github Link Here!\n  </a> \n  <a href=\"https://github.com/cosmostation/cvms/blob/release/docs/setup.md\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 CVMS Setup Guide Here!!\n  </a> \n</p>"
   }
  },
  {
   "title": "Indexer Sync Delay",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - cvms_root_index_pointer_timestamp{chain_id='$chain_id'}",
     "legendFormat": "{{package}}"
    }
   ]
  },
  { "title": "Block Data Analytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Block Gas Usage %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cvms_block_data_analytics_block_gas_used{chain_id='$chain_id'} / scalar(cvms_block_data_analytics_block_max_gas{chain_id='$chain_id'})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tx Bytes Usage %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(cvms_block_data_analytics_block_txs_bytes{chain_id='$chain_id'} / scalar(cvms_block_data_analytics_block_max_bytes{chain_id='$chain_id'})) * 100 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latest Blocks Info",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 9 },
   "targets": [
    {
     "rawSql": "select \n\tbda.height, \n\tbda.total_gas_used,\n\tbda.total_gas_wanted,\n\tbda.total_txs_bytes,\n\tbda.success_txs_count,\n\tbda.failed_txs_count\nfrom block_data_analytics_${table_chain_id} bda \nORDER BY height desc\nlimit 10;"
    }
   ]
  },
  { "title": "Amplifier Verifier Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Amplifier Verifier Indexed Vote Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "  \nSELECT vi.moniker,\n\tCOUNT(CASE WHEN status = 0 THEN 1 END) as \"DidNotVote\",\n\tSTRING_AGG(CASE WHEN status = 0 THEN chain_and_poll_id END, ', ') AS \"DidNotVotePolls\",\n\tCOUNT(CASE WHEN status = 1 THEN 1 END) as \"FailedOnChain\",\n\tSTRING_AGG(CASE WHEN status = 1 THEN chain_and_poll_id END, ', ') AS \"FailedOnChainPolls\",\n\tCOUNT(CASE WHEN status = 2 THEN 1 END) as \"NotFound\",\n\tSTRING_AGG(CASE WHEN status = 2 THEN chain_and_poll_id END, ', ') AS \"NotFoundPolls\",\n\tCOUNT(CASE WHEN status = 3 THEN 1 END) as \"SucceededOnChain\",\n\tSTRING_AGG(CASE WHEN status = 3 THEN chain_and_poll_id END, ', ') AS \"SucceededOnChainPolls\"\nFROM axelar_amplifier_verifier_${table_chain_id} idx\nJOIN meta.verifier_info vi ON idx.verifier_id  = vi.id\nWHERE\n  idx.poll_start_height > (\n    SELECT MAX(poll_start_height) - ${blocks}\n    FROM axelar_amplifier_verifier_${table_chain_id}\n  )\n  and idx.created_at < NOW() + INTERVAL '${interval_mins} minutes'\n\nGROUP BY vi.moniker;\n"
    }
   ]
  },
  {
   "title": "Amplifier Verifier Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  t1.poll_start_height,\n  t2.verifier_address,\n  t1.status,\n  t1.chain_and_poll_id,\n  t1.poll_vote_height\nFROM\n  axelar_amplifier_verifier_${table_chain_id} t1\nJOIN\n  meta.verifier_info t2\n  ON t1.verifier_id = t2.id\nWHERE\n  t1.poll_start_height > (\n    SELECT MAX(poll_start_height) - ${blocks}\n    FROM axelar_amplifier_verifier_${table_chain_id}\n  )\n  And t1.created_at < NOW() + INTERVAL '${interval_mins} minutes'\n\n"
    }
   ]
  },
  { "title": "CometBFT Validator Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Consensus Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 38, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": ";\nWITH max_height AS (\n  SELECT MAX(height) AS highest_height\n  FROM voteindexer_${table_chain_id}\n)\nSELECT\n  vidx.height,\n  vidx.status,\n  vi.moniker AS moniker\nFROM\n  voteindexer_${table_chain_id} vidx\nJOIN\n  meta.validator_info vi\n  ON vidx.validator_hex_address_id = vi.id\nJOIN\n  max_height mh  -- Join to get the maximum block height\n  ON vidx.height BETWEEN (mh.highest_height - ${blocks}) AND mh.highest_height\nORDER by\n  vidx.height ASC\n  \n  "
    }
   ]
  }
 ]
}